### ISSUE TITLE
Key adding dialog sometimes returns empty keypresses

### ISSUE THREAD

**Issue by daisyUniverse** [robinuniverse/Keebie#16]
I've noticed that if you use the hotkey adding dialog, if you do not hit the desired key quickly enough (within 1 second of the prompt appearing it feels like) it will try to bind to an empty key value. Not a huge issue but initially confusing

Also, I just wanna say that besides that, that menu works incredibly smoothly. Really nicely done @Michael-E-B

**Comment by Michael-E-B** [comment]
The shell should wait until the user starts pressing keys, and then wait one second before reading the device. But it would appear I didn't quite get that right, I should have a fix very shortly.

**Comment by Michael-E-B** [comment]
I think I found the problem, `--add` uses `InputDevice.read_loop()` which is a linear queue of events, the loop breaks when it reads an event while the time the loop has run is greater than the timeout.

This scheme can return when it still has events to process, `InputDevice.read_loop()` will often send multipule events at once, but if the timeout has passed (but the loop hasn't yet broken due to no new events) then only the first event will be processed.

The timestamp on each event may be useful for lumping events together for bulk processing may help resolve this issue, another solution would be to restart the loop if it ends with an empty key ledger.

**Comment by Michael-E-B** [comment]
More accurate steps to reproduce:

Use `--add` to launch the key addition shell, when prompted to press and hold a key combination press a key on the target board and release it, wait at least one second and then press a key on the target board (or otherwise trigger an event), the shell will return an incorrect list of keys.

**Comment by Michael-E-B** [comment]
Also the function can start before the user presses any key if there are any events in the queue when the loop starts.

**Comment by Michael-E-B** [comment]
The new system uses `InputDevice.read()` instead of `read_loop()` , this allows it to process events in batches.
