### ISSUE TITLE
Switch bounce?

### ISSUE THREAD

**Issue by TCPMeta** [robinuniverse/Keebie#22]
I added an entry into the default.json using the --add flag to load Sublime Text and assigned it to the SPACE key. When running and if I hit SPACE it will launch the program either three to five times as if there is a switch bounce. I tried a different keyboard and got the same issue. I also tried looking at the default.json and tried editing a few things and no change.

**CLI OUTPUT**
Welcome to Keebie
Loading settings from settings.json
: /opt/sublime_text/sublime_text&
KEY_SPACE: 
: /opt/sublime_text/sublime_text&
: /opt/sublime_text/sublime_text&
: /opt/sublime_text/sublime_text&
: /opt/sublime_text/sublime_text&

**DEFAULT.JSON**
{
   "leds": [],
   "vars": {
      "sublimetext": "/opt/sublime_text/sublime_text"
   },
   "KEY_SPACE": "%sublimetext",
   "": "/opt/sublime_text/sublime_text"
}

**Comment by Michael-E-B** [comment]
Try changing the line `"": "/opt/sublime_text/sublime_text"` to `"placeholder": "/opt/sublime_text/sublime_text"`.

Due to the way the `keyLedger` works whenever the keyboard sends an event while no keys are pressed the `keyLedger` gets updated and because no keys are pressed (or because nothing has changed) `ledger.getFresh(1)` will return an empty string matching `"": "/opt/sublime_text/sublime_text"` in your `default.json`, changing the empty string to something that won't come up will help test if this line is in fact the issue. If this solves the issue you can delete that line.

Also `"KEY_SPACE": "%sublimetext",` should be changed to `"KEY_SPACE": "%sublimetext%",` (note the second `%`); otherwise `parseVars()` will return `"` which won't do anything. You can see this in the output as `KEY_SPACE:` should be `KEY_SPACE: "/opt/sublime_text/sublime_text"`.

**Comment by Michael-E-B** [comment]
@TCPMeta, any update?

**Comment by Michael-E-B** [comment]
Given the lack new info I'm going to close his.
